### ISSUE TITLE
Project 'spfproxy' is missing required source folder: 'src'

### ISSUE THREAD

**Issue by sankalpkotewar** [clic-lab/spf#1]
Description	Resource	Path	Location	Type
Project 'spfproxy' is missing required source folder: 'src'	spfproxy		Build path	Build Path Problem

**Comment by yoavartzi** [comment]
You can just ignore it and remove it from the dependencies. It does not contain any meaningful code.

**Comment by sankalpkotewar** [comment]
Well, removing the dependency didn't work as it created a few new problems
(for geoquery, utils and unittests), but simply adding an empty "src"
folder inside spfproxy removed the problem.

Thanks :)



‌
