### ISSUE TITLE
Visualizing Semantic Graph

### ISSUE THREAD

**Issue by HoltSpalding** [clic-lab/spf#4]
Are there any methods allowing you to visualize the semantic graph produced by your CCG rules? Visualizing the parse trees was relatively straightforward but I need the actual graph representation of the relationship between my predicates and their arguments.

**Comment by yoavartzi** [comment]
We never treated the lambda calculus expressions as semantic graphs. There is no standard that I know of to represent unrestricted lambda calculus as graphs. However, it should be extremely easy to write a visitor that prints the logical form in whatever way you want. All operations on the logical forms use visitors, including their toString() function.
