### ISSUE TITLE
Coordinating "and"

### ISSUE THREAD

**Issue by HoltSpalding** [clic-lab/spf#5]
Hello,

I was wondering if there was a way to parse the following [sentence](https://www.inf.ed.ac.uk/teaching/courses/nlg/readings/ccgintro.pdf#page=3), "I loathe and detest opera" by means of a conjunctive "and". I don't want to have to define "and" for every possible set of leftward and rightward syntactic categories in my CCG lexicon. I've had no luck doing this, but I'd like to add such a rule if there isn't one already.Thank you.

**Comment by yoavartzi** [comment]
The general case of coordination is very complex. We have some level of coordination implemented, but it's not well documented. The rule that you will need to add to the parser is called [CoordinationRule](https://github.com/clic-lab/spf/blob/master/parser.ccg.rules.coordination/src/edu/cornell/cs/nlp/spf/parser/ccg/rules/coordination/CoordinationRule.java). 

It might take care of the case you mention, but I am not sure. Unfortunately, you will have to probably read this from the code. 

Alternatively, you can easily implement the general case as a new rule and add it to the parser.
